name: Sync
on:
  push:
    branches: [ hugo ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: lb19940508/git-mirror-action@master
      env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: "git@github.com:lb19940508/leobot.git"
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: "git@gitee.com:leobot/leobot.git"
    - name: Build Gitee Pages
      uses: lb19940508/gitee-pages-action@master
      with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: Leobot
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: leobot/leobot
